### PR TITLE
Stbi and Assimp reader

### PR DESCRIPTION
**Pull request by anormann1974**
Hi Robert,

this is the initial version of an assimp importer for vsg. Texture loading is done via stbi.

vsgconv is working.

### CODE REVIEW

**Comment by robertosfield** [comment]
I've merged and just started to try things.  First issue is that my Xubuntu 18.04 system's compiler isn't happy with:

**Comment by anormann1974** [comment]
Hi Robert,

std::filesystem is part of c++-17. So it should work out of the box.

**Comment by robertosfield** [comment]
Life isn't that easy I'm afraid.  The filesystem component of C++17 is not fully supported, it's placed under experimental. My compile is:

gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Back in the early days of the VSG I attempted to use filesystem and had to abandon it as it just wasn't consistently supported.

I've now compiled and installed assimp and have some more errors, again it's the compiler being bone headed:
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp: In constructor ‘vsgXchange::ReaderWriter_assimp::ReaderWriter_assimp()’:
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:231:10: warning: variable ‘readSpvFile’ set but not used [-Wunused-but-set-variable]
     auto readSpvFile = [](const uint32_t *content, size_t size, VkShaderStageFlagBits stage) -> vsg::ref_ptr<vsg::ShaderStage> {
          ^~~~~~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp: In lambda function:
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:440:134: warning: declaration of ‘const aiScene& scene’ shadows a parameter [-Wshadow]
     auto getTexture = [&](const aiScene &scene, aiMaterial &material, aiTextureType type, std::vector<std::string> &defines) -> vsg::SamplerImage {
                                                                                                                                      ^~~~~~~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:423:85: note: shadowed declaration is here
 ReaderWriter_assimp::BindState ReaderWriter_assimp::processMaterials(const aiScene *scene, vsg::ref_ptr<const vsg::Options> options) const
                                                                                     ^~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:442:117: warning: missing braces around initializer for ‘std::__array_traits<aiTextureMapMode, 3>::_Type {aka aiTextureMapMode [3]}’ [-Wmissing-braces]
         std::array<aiTextureMapMode, 3> wrapMode{aiTextureMapMode_Wrap, aiTextureMapMode_Wrap, aiTextureMapMode_Wrap};
                                                                                                                     ^
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:459:26: warning: declaration of ‘auto options’ shadows a parameter [-Wshadow]
                     auto options = vsg::Options::create(*_options);
                          ^~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:423:125: note: shadowed declaration is here
 ReaderWriter_assimp::BindState ReaderWriter_assimp::processMaterials(const aiScene *scene, vsg::ref_ptr<const vsg::Options> options) const
                                                                                                                             ^~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:510:53: error: ‘floorf’ is not a member of ‘std’
                 samplerImage.sampler->maxLod = std::floorf(std::log2f(static_cast<float>(maxDim)));
                                                     ^~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:510:53: note: suggested alternative: ‘floor’
                 samplerImage.sampler->maxLod = std::floorf(std::log2f(static_cast<float>(maxDim)));
                                                     ^~~~~~
                                                     floor

**Comment by robertosfield** [comment]
I haven't started looking at the code itself as I've been chasing VSG and OSG bugs today.  It's end of day here so am about to head offline. I'll have a look at resolving these compile issues tomorrow.

**Comment by robertosfield** [comment]
I have fixed the build errors, they were all pretty straight forward.   #68e327e752370133244e8a3140b39a233517817d

**Comment by anormann1974** [comment]
I will test it in a few minutes. I used iststream, because it will not create a copy of the input data. I know it is deprecated, but currently there is now replacement available, without creating a copy.

**Comment by anormann1974** [comment]
With Visual C++ I get now warning because of the GCC pragma's. I guess we need a #ifdef around them. Everything else is fine.

**Comment by robertosfield** [comment]
I will test with clang and come up with an appropriate guard for the pragma.  There are ones in the vsg::vec* headers that we can use as a guide,  The alternative is to fix the warnings in the stb_image.h but I'd rather use it as is so when we need to update from upstream it can be just dropped in.

With the istrstream replacement.  Not using deprecated functionality is part of making sure the VSG is future proofed.  It might be that come with our own streambuffer implementation.  At this point just getting something working reliably across all platforms has to be the priority,  We can revisit performance side if issues become critical.

**Comment by anormann1974** [comment]
That sounds good for me.

**Comment by robertosfield** [comment]
I have checked in the #ifdef's for gcc.  Could you test and let me know if it fixes the warning that the pragmas introduced.

 I had also added assim as a dependency for the vsgXchange cmake config files so that when you install vsgXchange and then use vsgXchange in your applications assim will automatically be found linked.  With this vsgExamples compiles correctly from scratch.

I still get some buld warnings:

/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp: In lambda function:
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:428:134: warning: declaration of ‘const aiScene& scene’ shadows a parameter [-Wshadow]
     auto getTexture = [&](const aiScene& scene, aiMaterial& material, aiTextureType type, std::vector<std::string>& defines) -> vsg::SamplerImage {
                                                                                                                                      ^~~~~~~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:411:85: note: shadowed declaration is here
 ReaderWriter_assimp::BindState ReaderWriter_assimp::processMaterials(const aiScene* scene, vsg::ref_ptr<const vsg::Options> options) const
                                                                                     ^~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:448:26: warning: declaration of ‘auto options’ shadows a parameter [-Wshadow]
                     auto options = vsg::Options::create(*_options);
                          ^~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:411:125: note: shadowed declaration is here
 ReaderWriter_assimp::BindState ReaderWriter_assimp::processMaterials(const aiScene* scene, vsg::ref_ptr<const vsg::Options> options) const
                                                                                                                             ^~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp: In member function ‘vsgXchange::ReaderWriter_assimp::BindState vsgXchange::ReaderWriter_assimp::processMaterials(const aiScene*, vsg::ref_ptr<const vsg::Options>) const’:
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:672:27: warning: declaration of ‘samplerImage’ shadows a previous local [-Wshadow]
             else if (auto samplerImage = getTexture(*scene, *material, aiTextureType_AMBIENT, defines); samplerImage.data.valid())
                           ^~~~~~~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:666:22: note: shadowed declaration is here
             if (auto samplerImage = getTexture(*scene, *material, aiTextureType_LIGHTMAP, defines); samplerImage.data.valid())
                      ^~~~~~~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:611:24: warning: unused variable ‘ambientResult’ [-Wunused-variable]
             const auto ambientResult = material->Get(AI_MATKEY_COLOR_AMBIENT, mat.ambient);
                        ^~~~~~~~~~~~~
[ 89%] Linking CXX static library ../lib/libvsgXchange.a

I'd like to get vsgXchange compiling cleanly before merging the Assim branch with master.

**Comment by anormann1974** [comment]
I created another pull request, which should fix the warnings.

**Pull request merged**
