### PR TITLE
Fixed compiler warnings

### PR DESCRIPTION
**Pull request by anormann1974**

### CODE REVIEW

**Comment by anormann1974** [comment]
Hi Robert, this should fix your last compiler warnings.

**Comment by robertosfield** [comment]
Thanks.  Most of the warnings are now fixed, but have this last one:

/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:674:27: warning: declaration of ‘samplerImage’ shadows a previous local [-Wshadow]
             else if (auto samplerImage = getTexture(*material, aiTextureType_AMBIENT, defines); samplerImage.data.valid())
                           ^~~~~~~~~~~~
/home/robert/Dev/vsgXchange/src/assimp/ReaderWriter_assimp.cpp:668:22: note: shadowed declaration is here
             if (auto samplerImage = getTexture(*material, aiTextureType_LIGHTMAP, defines); samplerImage.data.valid())
                      ^~~~~~~~~~~~

BTW, I've started testing with .gltf models but don't see any PBR on the class damaged helment, should I be expecting it to be PBR out of the box?  I haven't walked through the code properly yet so I guess the answer is probably hidden away in there.

**Comment by anormann1974** [comment]
To fix this warning, simple remove the "auto" in line 674.

**Comment by anormann1974** [comment]
Yes, PBR should work out of the box. Could you try the binary version of the damaged helmet (*.glb)?

**Comment by robertosfield** [comment]
Looks like there is more that one auto samplerImage so me thinks I'd have to modify more than one line.  The code looks correct, the compiler is being a bit over enthusiastic...  for now we can just ignore.  Tomorrow I might have a thinker to see if I can quieten and not affect the nature of the code.

On the PBR front the .glb does give me PBR :-)

I will need to review the shaders and how they are set up tomorrow as well.  I need to have a general think about how to present this type of functionality to users, cache shaders, handling lighting and environment maps etc is a standard way as this will become more of hot topic once people start to combine many models into a single world scene.

Cheers,
Robert.

**Comment by anormann1974** [comment]
I guess the texture files could not be found, when using the *.gltf file. "vsgconv file.gltf" may not work, but "vsgconv ./file.gltf" will work.

**Comment by robertosfield** [comment]
On Sun, 24 Jan 2021 at 18:15, Andre Normann <notifications@github.com>
wrote:

> I guess the texture files could not be found, when using the *.gltf file.
> "vsgconv file.gltf" may not work, but "vsgconv ./file.gltf" will work.
>
Thanks for the pointer.  I'm heading offline now.  Tomorrow I'll dig in
some more.

Things search paths, case sensitivity or checks will all need to refined,
no need to try and resolve everything in one day.  I'm pretty chuffed that
we are as far along as we are.  Thanks for your efforts.

**Pull request merged**
