### PR TITLE
changed std::unique_ptr<Implementation> to Implementation* 

### PR DESCRIPTION
**Pull request by LaurensVoerman**
for forward declared implementations.

### CODE REVIEW

**Comment by LaurensVoerman** [comment]
Maybe this should not be merged. While it compiles I think it will crash as the raw pointers are not initialized.

**Comment by LaurensVoerman** [comment]
Added the init and delete, only the curl plugin would have a problem without.

**Comment by robertosfield** [comment]
Thanks for the this work @LaurensVoerman , much appreciated.

Does this mean the vsgXchange now works properly on Windows with a DLL build?

I have done a first pass review.  Looks good.  After merging I'll go through a make two refinements:

   Put the destructors into protected scope to avoid users create the ReaderWriter's on the heap.
   Remove the if (_implement) as delete works safely when passed a nullptr.

I mention these two changes just you know the reason for the changes.

**Comment by robertosfield** [comment]
The two commits to move the destructors into protected scope and to remove the unnecessary if () and delete calls.

8b2b9688dbcf8415502790b6b4c0f1b99cf96c5b
e217cca4b1a1d9fe1c28e614df1196d4e61b8012

**Pull request merged**
