### PR TITLE
Increase required minimum OSG version to 3.6 as #72 depends on that version

### PR DESCRIPTION
**Pull request by rhabacker**

### CODE REVIEW

**Comment by robertosfield** [comment]
Oh dear, I didn't spot the osg::TemplatePrimitiveIndexFunctor was an addition to 3.6.  

I'd rather not make OSG-3.6 a requirement, so perhaps implementing more of the code  that the template provides in the vsgXchange would be a way around this.  I'm currently busy debugging multie-device support in the VSG, once that's done and checked it I'll have a look at getting vsgXchange to compile against older than OSG 3.6 versions.

**Comment by robertosfield** [comment]
@rhabacker I've had a bash at getting vsgXchange osg ReaderWriter to compile against OSG-3.4 but it failed due to a number of issues so have decided to abandon trying to get it compile so will merge your suggestion.  A bit sad to loose 3.4 support but trying to keep it compiling would push awkward code into vsgXchange.

**Comment by robertosfield** [comment]
@rhabacker I've merged your change and tried out vsgXchange building with OpenSceneGraph-3.4 available but it doesn't pick up on the version requirement so still builds despite only having 3.4 available.

What platform combination did you test against?

**Comment by rhabacker** [comment]
I think this is because the current cmake find package support of [osg](https://github.com/Kitware/CMake/blob/master/Modules/Findosg.cmake) does not include version checking.

**Comment by rhabacker** [comment]
And using `find_package(OpenSceneGraph ...)` only partially fixes the problem, since according to https://github.com/Kitware/CMake/blob/68b0c62a72a4d3352ed909c208400d02e65a4b61/Modules/FindOpenSceneGraph.cmake#L176 it returns the variable `OPENSCENEGRAPH_VERSION` with the found version, but does not compare it with OSG_FIND_VERSION.

**Pull request merged**
